/********************************************************************************
** Form generated from reading UI file 'Helll_Player_UI.ui'
**
** Created: Wed 20. Jun 02:30:04 2012
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HELLL_H
#define UI_HELLL_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDial>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLCDNumber>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListWidget>
#include <QtGui/QMainWindow>
#include <QtGui/QProgressBar>
#include <QtGui/QPushButton>
#include <QtGui/QSlider>
#include <QtGui/QStatusBar>
#include <QtGui/QTableView>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *mainWindow;
    QTableView *wreverbTable;
    QLabel *wreverbTxt;
    QTableView *echoTable;
    QTableView *flangerTable;
    QTableView *chorusTable;
    QTableView *gargleTable;
    QTableView *distTable;
    QProgressBar *timeBar;
    QLabel *echoTxt;
    QLabel *flangerTxt;
    QLabel *chorusTxt;
    QLabel *gargleTxt;
    QLabel *distTxt;
    QLCDNumber *clockMin;
    QDial *wreverbHFTimeRatio;
    QDial *wreverbGain;
    QDial *wreverbMix;
    QDial *wreverbTime;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QSlider *volumeSlider;
    QTableView *slidersTableView;
    QSlider *pbspeedSlider;
    QLabel *label_5;
    QLabel *label_6;
    QPushButton *playButton;
    QPushButton *wreverbOnOff;
    QPushButton *flangerOnOff;
    QPushButton *distOnOff;
    QPushButton *gargleOnOff;
    QPushButton *chorusOnOff;
    QPushButton *echoOnOff;
    QPushButton *stopButton;
    QPushButton *previousButton;
    QPushButton *nextButton;
    QPushButton *addFilesButton;
    QPushButton *disableAllButton;
    QTableView *copyrightTableView;
    QLabel *label_7;
    QDial *flangerWDMix;
    QDial *flangerDepth;
    QDial *flangerFreq;
    QDial *flangerTWForm;
    QDial *flangerFDBack;
    QDial *flangerDelay;
    QDial *flangerPhase;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QDial *distGain;
    QLabel *label_16;
    QDial *distEdge;
    QLabel *label_17;
    QDial *distPEQCFreq;
    QLabel *label_18;
    QDial *distPEQBandw;
    QLabel *label_19;
    QDial *distPreLPCutOff;
    QLabel *label_20;
    QDial *gargleRateHZ;
    QLabel *label_21;
    QDial *gargleSWForm;
    QLabel *label_22;
    QDial *echoWDMix;
    QLabel *label_23;
    QDial *echoFDBack;
    QLabel *label_24;
    QDial *echoLDelay;
    QLabel *label_25;
    QDial *echoRDelay;
    QLabel *label_26;
    QDial *echoPanDelay;
    QLabel *label_27;
    QDial *chorusWDMix;
    QLabel *label_28;
    QDial *chorusDepth;
    QLabel *label_29;
    QDial *chorusFDBack;
    QLabel *label_30;
    QDial *chorusFreq;
    QLabel *label_31;
    QDial *chorusDelay;
    QLabel *label_32;
    QDial *chorusSWForm;
    QLabel *label_33;
    QDial *chorusPhase;
    QLabel *label_34;
    QCheckBox *keepVolume;
    QCheckBox *keepPBSpeed;
    QCheckBox *keepEffectsOn;
    QFrame *line;
    QLCDNumber *volumeLCD;
    QLCDNumber *pbspeedLCD;
    QTableView *compTable;
    QLabel *compTxt;
    QListWidget *playList;
    QTableView *playlistParamTableView;
    QCheckBox *randomPlaying;
    QCheckBox *invertPlaySeq;
    QCheckBox *startTrackPaused;
    QPushButton *deleteTracks;
    QPushButton *savePlayList;
    QPushButton *loadPlayList;
    QCheckBox *repeatTrack;
    QDial *compGain;
    QDial *compAttack;
    QDial *compRelease;
    QDial *compRatio;
    QDial *compPreDelay;
    QDial *compThreshold;
    QPushButton *compOnOff;
    QLabel *label_8;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QSlider *playposSlider;
    QLabel *label_40;
    QLCDNumber *clockSec;
    QLCDNumber *clockMinMax;
    QLCDNumber *clockSecMax;
    QLineEdit *trackInfo1;
    QLineEdit *trackInfo2;
    QLineEdit *sysInfo1;
    QLineEdit *sysInfo2;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->setEnabled(true);
        MainWindow->resize(861, 698);
        QIcon icon;
        icon.addFile(QString::fromUtf8("../../Program Files/Helll Player v5.15b/fire.ico"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        MainWindow->setWindowOpacity(95);
        MainWindow->setStyleSheet(QString::fromUtf8("QMainWindow\n"
"{\n"
"background-image : url(chaos_realm.jpg)\n"
"}"));
        mainWindow = new QWidget(MainWindow);
        mainWindow->setObjectName(QString::fromUtf8("mainWindow"));
        wreverbTable = new QTableView(mainWindow);
        wreverbTable->setObjectName(QString::fromUtf8("wreverbTable"));
        wreverbTable->setGeometry(QRect(10, 10, 271, 91));
        wreverbTable->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.0282486 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"));
        wreverbTxt = new QLabel(mainWindow);
        wreverbTxt->setObjectName(QString::fromUtf8("wreverbTxt"));
        wreverbTxt->setGeometry(QRect(20, 10, 91, 21));
        wreverbTxt->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        echoTable = new QTableView(mainWindow);
        echoTable->setObjectName(QString::fromUtf8("echoTable"));
        echoTable->setGeometry(QRect(290, 10, 271, 91));
        echoTable->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.0282486 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"));
        flangerTable = new QTableView(mainWindow);
        flangerTable->setObjectName(QString::fromUtf8("flangerTable"));
        flangerTable->setGeometry(QRect(10, 110, 271, 91));
        flangerTable->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.0282486 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"));
        chorusTable = new QTableView(mainWindow);
        chorusTable->setObjectName(QString::fromUtf8("chorusTable"));
        chorusTable->setGeometry(QRect(10, 210, 271, 91));
        chorusTable->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.0282486 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"));
        gargleTable = new QTableView(mainWindow);
        gargleTable->setObjectName(QString::fromUtf8("gargleTable"));
        gargleTable->setGeometry(QRect(10, 310, 271, 91));
        gargleTable->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.0282486 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
""));
        distTable = new QTableView(mainWindow);
        distTable->setObjectName(QString::fromUtf8("distTable"));
        distTable->setGeometry(QRect(10, 410, 271, 91));
        distTable->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0); \n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.0282486 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
""));
        timeBar = new QProgressBar(mainWindow);
        timeBar->setObjectName(QString::fromUtf8("timeBar"));
        timeBar->setGeometry(QRect(300, 190, 461, 21));
        timeBar->setStyleSheet(QString::fromUtf8("color: rgb(159, 0, 0);\n"
"alternate-background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.472, stop:0 rgba(0, 0, 0, 236), stop:1 rgba(255, 255, 255, 255));\n"
""));
        timeBar->setValue(0);
        timeBar->setTextVisible(false);
        echoTxt = new QLabel(mainWindow);
        echoTxt->setObjectName(QString::fromUtf8("echoTxt"));
        echoTxt->setGeometry(QRect(300, 10, 81, 16));
        echoTxt->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        flangerTxt = new QLabel(mainWindow);
        flangerTxt->setObjectName(QString::fromUtf8("flangerTxt"));
        flangerTxt->setGeometry(QRect(20, 110, 46, 16));
        flangerTxt->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        chorusTxt = new QLabel(mainWindow);
        chorusTxt->setObjectName(QString::fromUtf8("chorusTxt"));
        chorusTxt->setGeometry(QRect(20, 210, 71, 16));
        chorusTxt->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        gargleTxt = new QLabel(mainWindow);
        gargleTxt->setObjectName(QString::fromUtf8("gargleTxt"));
        gargleTxt->setGeometry(QRect(20, 310, 46, 21));
        gargleTxt->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        distTxt = new QLabel(mainWindow);
        distTxt->setObjectName(QString::fromUtf8("distTxt"));
        distTxt->setGeometry(QRect(20, 410, 51, 21));
        distTxt->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        clockMin = new QLCDNumber(mainWindow);
        clockMin->setObjectName(QString::fromUtf8("clockMin"));
        clockMin->setGeometry(QRect(770, 180, 40, 21));
        clockMin->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 73, 73);\n"
""));
        clockMin->setNumDigits(3);
        wreverbHFTimeRatio = new QDial(mainWindow);
        wreverbHFTimeRatio->setObjectName(QString::fromUtf8("wreverbHFTimeRatio"));
        wreverbHFTimeRatio->setGeometry(QRect(170, 50, 41, 41));
        wreverbHFTimeRatio->setMinimum(1);
        wreverbHFTimeRatio->setMaximum(999);
        wreverbHFTimeRatio->setPageStep(1);
        wreverbGain = new QDial(mainWindow);
        wreverbGain->setObjectName(QString::fromUtf8("wreverbGain"));
        wreverbGain->setGeometry(QRect(20, 50, 41, 41));
        wreverbGain->setMinimum(-96);
        wreverbGain->setMaximum(0);
        wreverbGain->setPageStep(1);
        wreverbMix = new QDial(mainWindow);
        wreverbMix->setObjectName(QString::fromUtf8("wreverbMix"));
        wreverbMix->setGeometry(QRect(60, 50, 41, 41));
        wreverbMix->setMinimum(-100);
        wreverbMix->setMaximum(0);
        wreverbMix->setPageStep(1);
        wreverbMix->setValue(-70);
        wreverbTime = new QDial(mainWindow);
        wreverbTime->setObjectName(QString::fromUtf8("wreverbTime"));
        wreverbTime->setGeometry(QRect(100, 50, 41, 41));
        wreverbTime->setMinimum(1);
        wreverbTime->setMaximum(3000000);
        wreverbTime->setSingleStep(10);
        wreverbTime->setValue(1000000);
        label = new QLabel(mainWindow);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(30, 40, 21, 16));
        label->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_2 = new QLabel(mainWindow);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(70, 40, 21, 16));
        label_2->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_3 = new QLabel(mainWindow);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(100, 40, 51, 16));
        label_3->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_4 = new QLabel(mainWindow);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(160, 40, 71, 16));
        label_4->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        volumeSlider = new QSlider(mainWindow);
        volumeSlider->setObjectName(QString::fromUtf8("volumeSlider"));
        volumeSlider->setGeometry(QRect(340, 330, 31, 211));
        volumeSlider->setCursor(QCursor(Qt::ArrowCursor));
        volumeSlider->setAcceptDrops(true);
        volumeSlider->setStyleSheet(QString::fromUtf8("background-color: rgb(155, 155, 155);\n"
"color: rgb(255, 0, 0);"));
        volumeSlider->setMaximum(100);
        volumeSlider->setPageStep(1);
        volumeSlider->setValue(65);
        volumeSlider->setOrientation(Qt::Vertical);
        volumeSlider->setTickPosition(QSlider::NoTicks);
        slidersTableView = new QTableView(mainWindow);
        slidersTableView->setObjectName(QString::fromUtf8("slidersTableView"));
        slidersTableView->setGeometry(QRect(300, 320, 191, 281));
        slidersTableView->setStyleSheet(QString::fromUtf8("background-color: rgb(169, 169, 169);"));
        pbspeedSlider = new QSlider(mainWindow);
        pbspeedSlider->setObjectName(QString::fromUtf8("pbspeedSlider"));
        pbspeedSlider->setGeometry(QRect(420, 330, 31, 211));
        pbspeedSlider->setCursor(QCursor(Qt::ArrowCursor));
        pbspeedSlider->setAcceptDrops(true);
        pbspeedSlider->setStyleSheet(QString::fromUtf8("background-color: rgb(155, 155, 155);"));
        pbspeedSlider->setMinimum(1);
        pbspeedSlider->setMaximum(300);
        pbspeedSlider->setPageStep(1);
        pbspeedSlider->setSliderPosition(100);
        pbspeedSlider->setOrientation(Qt::Vertical);
        label_5 = new QLabel(mainWindow);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(330, 540, 51, 16));
        label_5->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(18, 18, 18);"));
        label_6 = new QLabel(mainWindow);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(400, 540, 71, 16));
        label_6->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:, x2:0, y2:, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(18, 18, 18);"));
        playButton = new QPushButton(mainWindow);
        playButton->setObjectName(QString::fromUtf8("playButton"));
        playButton->setGeometry(QRect(300, 230, 91, 31));
        playButton->setStyleSheet(QString::fromUtf8("font: 75 8pt \"MS Shell Dlg 2\";"));
        wreverbOnOff = new QPushButton(mainWindow);
        wreverbOnOff->setObjectName(QString::fromUtf8("wreverbOnOff"));
        wreverbOnOff->setGeometry(QRect(220, 70, 51, 24));
        flangerOnOff = new QPushButton(mainWindow);
        flangerOnOff->setObjectName(QString::fromUtf8("flangerOnOff"));
        flangerOnOff->setGeometry(QRect(220, 170, 51, 24));
        distOnOff = new QPushButton(mainWindow);
        distOnOff->setObjectName(QString::fromUtf8("distOnOff"));
        distOnOff->setGeometry(QRect(220, 270, 51, 24));
        gargleOnOff = new QPushButton(mainWindow);
        gargleOnOff->setObjectName(QString::fromUtf8("gargleOnOff"));
        gargleOnOff->setGeometry(QRect(220, 370, 51, 24));
        chorusOnOff = new QPushButton(mainWindow);
        chorusOnOff->setObjectName(QString::fromUtf8("chorusOnOff"));
        chorusOnOff->setGeometry(QRect(220, 470, 51, 24));
        echoOnOff = new QPushButton(mainWindow);
        echoOnOff->setObjectName(QString::fromUtf8("echoOnOff"));
        echoOnOff->setGeometry(QRect(500, 70, 51, 24));
        stopButton = new QPushButton(mainWindow);
        stopButton->setObjectName(QString::fromUtf8("stopButton"));
        stopButton->setGeometry(QRect(399, 230, 91, 31));
        previousButton = new QPushButton(mainWindow);
        previousButton->setObjectName(QString::fromUtf8("previousButton"));
        previousButton->setGeometry(QRect(300, 270, 91, 31));
        nextButton = new QPushButton(mainWindow);
        nextButton->setObjectName(QString::fromUtf8("nextButton"));
        nextButton->setGeometry(QRect(399, 270, 91, 31));
        addFilesButton = new QPushButton(mainWindow);
        addFilesButton->setObjectName(QString::fromUtf8("addFilesButton"));
        addFilesButton->setGeometry(QRect(510, 570, 91, 31));
        disableAllButton = new QPushButton(mainWindow);
        disableAllButton->setObjectName(QString::fromUtf8("disableAllButton"));
        disableAllButton->setGeometry(QRect(70, 510, 141, 41));
        copyrightTableView = new QTableView(mainWindow);
        copyrightTableView->setObjectName(QString::fromUtf8("copyrightTableView"));
        copyrightTableView->setGeometry(QRect(10, 570, 261, 51));
        copyrightTableView->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.472, stop:0 rgba(0, 0, 0, 203), stop:1 rgba(255, 255, 255, 255));"));
        label_7 = new QLabel(mainWindow);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 580, 241, 21));
        flangerWDMix = new QDial(mainWindow);
        flangerWDMix->setObjectName(QString::fromUtf8("flangerWDMix"));
        flangerWDMix->setGeometry(QRect(20, 160, 41, 41));
        flangerWDMix->setMaximum(100);
        flangerWDMix->setPageStep(1);
        flangerWDMix->setValue(50);
        flangerDepth = new QDial(mainWindow);
        flangerDepth->setObjectName(QString::fromUtf8("flangerDepth"));
        flangerDepth->setGeometry(QRect(70, 160, 41, 41));
        flangerDepth->setMaximum(100);
        flangerDepth->setPageStep(1);
        flangerDepth->setValue(100);
        flangerFreq = new QDial(mainWindow);
        flangerFreq->setObjectName(QString::fromUtf8("flangerFreq"));
        flangerFreq->setGeometry(QRect(120, 160, 41, 41));
        flangerFreq->setMaximum(1000);
        flangerFreq->setPageStep(2);
        flangerFreq->setValue(25);
        flangerTWForm = new QDial(mainWindow);
        flangerTWForm->setObjectName(QString::fromUtf8("flangerTWForm"));
        flangerTWForm->setGeometry(QRect(170, 160, 41, 41));
        flangerTWForm->setMaximum(1);
        flangerTWForm->setPageStep(1);
        flangerTWForm->setValue(1);
        flangerFDBack = new QDial(mainWindow);
        flangerFDBack->setObjectName(QString::fromUtf8("flangerFDBack"));
        flangerFDBack->setGeometry(QRect(100, 110, 41, 41));
        flangerFDBack->setMinimum(-99);
        flangerFDBack->setPageStep(2);
        flangerFDBack->setValue(-50);
        flangerDelay = new QDial(mainWindow);
        flangerDelay->setObjectName(QString::fromUtf8("flangerDelay"));
        flangerDelay->setGeometry(QRect(180, 110, 41, 41));
        flangerDelay->setMaximum(200);
        flangerDelay->setPageStep(1);
        flangerDelay->setValue(20);
        flangerPhase = new QDial(mainWindow);
        flangerPhase->setObjectName(QString::fromUtf8("flangerPhase"));
        flangerPhase->setGeometry(QRect(220, 130, 41, 41));
        flangerPhase->setMinimum(-180);
        flangerPhase->setMaximum(180);
        flangerPhase->setSingleStep(90);
        flangerPhase->setPageStep(90);
        flangerPhase->setWrapping(true);
        flangerPhase->setNotchesVisible(false);
        label_9 = new QLabel(mainWindow);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 150, 41, 16));
        label_9->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_10 = new QLabel(mainWindow);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(80, 150, 31, 16));
        label_10->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_11 = new QLabel(mainWindow);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(70, 120, 41, 16));
        label_11->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_12 = new QLabel(mainWindow);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(130, 150, 31, 16));
        label_12->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_13 = new QLabel(mainWindow);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(170, 150, 41, 16));
        label_13->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_14 = new QLabel(mainWindow);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(150, 120, 31, 16));
        label_15 = new QLabel(mainWindow);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(230, 120, 31, 16));
        distGain = new QDial(mainWindow);
        distGain->setObjectName(QString::fromUtf8("distGain"));
        distGain->setGeometry(QRect(20, 250, 41, 41));
        distGain->setMinimum(-60);
        distGain->setMaximum(0);
        distGain->setPageStep(1);
        distGain->setValue(-18);
        label_16 = new QLabel(mainWindow);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(30, 240, 21, 16));
        label_16->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        distEdge = new QDial(mainWindow);
        distEdge->setObjectName(QString::fromUtf8("distEdge"));
        distEdge->setGeometry(QRect(60, 250, 41, 41));
        distEdge->setMaximum(100);
        distEdge->setPageStep(1);
        distEdge->setValue(15);
        label_17 = new QLabel(mainWindow);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(70, 240, 31, 16));
        label_17->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        distPEQCFreq = new QDial(mainWindow);
        distPEQCFreq->setObjectName(QString::fromUtf8("distPEQCFreq"));
        distPEQCFreq->setGeometry(QRect(110, 240, 41, 41));
        distPEQCFreq->setMinimum(100);
        distPEQCFreq->setMaximum(8000);
        distPEQCFreq->setPageStep(50);
        distPEQCFreq->setValue(2400);
        label_18 = new QLabel(mainWindow);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(100, 230, 51, 16));
        label_18->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        distPEQBandw = new QDial(mainWindow);
        distPEQBandw->setObjectName(QString::fromUtf8("distPEQBandw"));
        distPEQBandw->setGeometry(QRect(160, 250, 41, 41));
        distPEQBandw->setMinimum(100);
        distPEQBandw->setMaximum(8000);
        distPEQBandw->setPageStep(50);
        distPEQBandw->setValue(2400);
        label_19 = new QLabel(mainWindow);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(160, 240, 61, 16));
        label_19->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        distPreLPCutOff = new QDial(mainWindow);
        distPreLPCutOff->setObjectName(QString::fromUtf8("distPreLPCutOff"));
        distPreLPCutOff->setGeometry(QRect(220, 230, 41, 41));
        distPreLPCutOff->setMinimum(100);
        distPreLPCutOff->setMaximum(8000);
        distPreLPCutOff->setPageStep(50);
        distPreLPCutOff->setValue(8000);
        label_20 = new QLabel(mainWindow);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(210, 220, 61, 16));
        label_20->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        gargleRateHZ = new QDial(mainWindow);
        gargleRateHZ->setObjectName(QString::fromUtf8("gargleRateHZ"));
        gargleRateHZ->setGeometry(QRect(70, 320, 61, 61));
        gargleRateHZ->setMinimum(1);
        gargleRateHZ->setMaximum(1000);
        gargleRateHZ->setPageStep(2);
        gargleRateHZ->setValue(20);
        label_21 = new QLabel(mainWindow);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(30, 340, 41, 16));
        label_21->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        gargleSWForm = new QDial(mainWindow);
        gargleSWForm->setObjectName(QString::fromUtf8("gargleSWForm"));
        gargleSWForm->setGeometry(QRect(160, 340, 41, 41));
        gargleSWForm->setMaximum(1);
        gargleSWForm->setPageStep(1);
        gargleSWForm->setValue(1);
        label_22 = new QLabel(mainWindow);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(160, 330, 41, 16));
        label_22->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        echoWDMix = new QDial(mainWindow);
        echoWDMix->setObjectName(QString::fromUtf8("echoWDMix"));
        echoWDMix->setGeometry(QRect(300, 50, 41, 41));
        echoWDMix->setMaximum(100);
        echoWDMix->setPageStep(1);
        echoWDMix->setValue(75);
        label_23 = new QLabel(mainWindow);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(300, 40, 41, 16));
        label_23->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        echoFDBack = new QDial(mainWindow);
        echoFDBack->setObjectName(QString::fromUtf8("echoFDBack"));
        echoFDBack->setGeometry(QRect(350, 50, 41, 41));
        echoFDBack->setMaximum(100);
        echoFDBack->setPageStep(1);
        echoFDBack->setValue(50);
        label_24 = new QLabel(mainWindow);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(350, 40, 41, 16));
        label_24->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        echoLDelay = new QDial(mainWindow);
        echoLDelay->setObjectName(QString::fromUtf8("echoLDelay"));
        echoLDelay->setGeometry(QRect(400, 50, 41, 41));
        echoLDelay->setMinimum(1);
        echoLDelay->setMaximum(2000);
        echoLDelay->setValue(390);
        label_25 = new QLabel(mainWindow);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(400, 40, 41, 16));
        label_25->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        echoRDelay = new QDial(mainWindow);
        echoRDelay->setObjectName(QString::fromUtf8("echoRDelay"));
        echoRDelay->setGeometry(QRect(450, 50, 41, 41));
        echoRDelay->setMinimum(1);
        echoRDelay->setMaximum(2000);
        echoRDelay->setValue(390);
        label_26 = new QLabel(mainWindow);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(450, 40, 41, 16));
        label_26->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        echoPanDelay = new QDial(mainWindow);
        echoPanDelay->setObjectName(QString::fromUtf8("echoPanDelay"));
        echoPanDelay->setGeometry(QRect(490, 30, 41, 41));
        echoPanDelay->setMaximum(1);
        echoPanDelay->setPageStep(1);
        label_27 = new QLabel(mainWindow);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(480, 20, 51, 20));
        label_27->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        chorusWDMix = new QDial(mainWindow);
        chorusWDMix->setObjectName(QString::fromUtf8("chorusWDMix"));
        chorusWDMix->setGeometry(QRect(20, 460, 41, 41));
        chorusWDMix->setMaximum(100);
        chorusWDMix->setPageStep(1);
        chorusWDMix->setValue(50);
        label_28 = new QLabel(mainWindow);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(30, 450, 41, 16));
        label_28->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        chorusDepth = new QDial(mainWindow);
        chorusDepth->setObjectName(QString::fromUtf8("chorusDepth"));
        chorusDepth->setGeometry(QRect(70, 460, 41, 41));
        chorusDepth->setMaximum(100);
        chorusDepth->setPageStep(1);
        chorusDepth->setValue(10);
        label_29 = new QLabel(mainWindow);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(80, 450, 31, 16));
        label_29->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        chorusFDBack = new QDial(mainWindow);
        chorusFDBack->setObjectName(QString::fromUtf8("chorusFDBack"));
        chorusFDBack->setGeometry(QRect(100, 410, 41, 41));
        chorusFDBack->setMinimum(-99);
        chorusFDBack->setPageStep(1);
        chorusFDBack->setValue(25);
        label_30 = new QLabel(mainWindow);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(70, 420, 41, 16));
        label_30->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        chorusFreq = new QDial(mainWindow);
        chorusFreq->setObjectName(QString::fromUtf8("chorusFreq"));
        chorusFreq->setGeometry(QRect(120, 460, 41, 41));
        chorusFreq->setMaximum(100);
        chorusFreq->setPageStep(1);
        chorusFreq->setValue(11);
        label_31 = new QLabel(mainWindow);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(130, 450, 31, 16));
        label_31->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        chorusDelay = new QDial(mainWindow);
        chorusDelay->setObjectName(QString::fromUtf8("chorusDelay"));
        chorusDelay->setGeometry(QRect(180, 410, 41, 41));
        chorusDelay->setMaximum(200);
        chorusDelay->setPageStep(2);
        chorusDelay->setValue(160);
        label_32 = new QLabel(mainWindow);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(150, 420, 31, 16));
        chorusSWForm = new QDial(mainWindow);
        chorusSWForm->setObjectName(QString::fromUtf8("chorusSWForm"));
        chorusSWForm->setGeometry(QRect(170, 460, 41, 41));
        chorusSWForm->setMaximum(1);
        chorusSWForm->setPageStep(1);
        chorusSWForm->setValue(1);
        label_33 = new QLabel(mainWindow);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(170, 450, 41, 16));
        label_33->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        chorusPhase = new QDial(mainWindow);
        chorusPhase->setObjectName(QString::fromUtf8("chorusPhase"));
        chorusPhase->setGeometry(QRect(220, 430, 41, 41));
        chorusPhase->setMinimum(-180);
        chorusPhase->setMaximum(180);
        chorusPhase->setSingleStep(1);
        chorusPhase->setPageStep(90);
        chorusPhase->setValue(90);
        label_34 = new QLabel(mainWindow);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(230, 420, 31, 16));
        keepVolume = new QCheckBox(mainWindow);
        keepVolume->setObjectName(QString::fromUtf8("keepVolume"));
        keepVolume->setGeometry(QRect(300, 560, 81, 21));
        keepVolume->setChecked(true);
        keepPBSpeed = new QCheckBox(mainWindow);
        keepPBSpeed->setObjectName(QString::fromUtf8("keepPBSpeed"));
        keepPBSpeed->setGeometry(QRect(400, 560, 91, 21));
        keepEffectsOn = new QCheckBox(mainWindow);
        keepEffectsOn->setObjectName(QString::fromUtf8("keepEffectsOn"));
        keepEffectsOn->setGeometry(QRect(300, 580, 101, 21));
        keepEffectsOn->setCheckable(true);
        keepEffectsOn->setTristate(false);
        line = new QFrame(mainWindow);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(300, 550, 191, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        volumeLCD = new QLCDNumber(mainWindow);
        volumeLCD->setObjectName(QString::fromUtf8("volumeLCD"));
        volumeLCD->setGeometry(QRect(300, 330, 31, 23));
        volumeLCD->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 119, 119);"));
        volumeLCD->setLineWidth(0);
        volumeLCD->setMidLineWidth(0);
        volumeLCD->setNumDigits(3);
        pbspeedLCD = new QLCDNumber(mainWindow);
        pbspeedLCD->setObjectName(QString::fromUtf8("pbspeedLCD"));
        pbspeedLCD->setGeometry(QRect(460, 330, 31, 23));
        pbspeedLCD->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 119, 119);"));
        pbspeedLCD->setLineWidth(0);
        pbspeedLCD->setNumDigits(3);
        compTable = new QTableView(mainWindow);
        compTable->setObjectName(QString::fromUtf8("compTable"));
        compTable->setEnabled(true);
        compTable->setGeometry(QRect(570, 10, 281, 91));
        compTable->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.0282486 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"));
        compTxt = new QLabel(mainWindow);
        compTxt->setObjectName(QString::fromUtf8("compTxt"));
        compTxt->setGeometry(QRect(580, 10, 81, 16));
        compTxt->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        playList = new QListWidget(mainWindow);
        playList->setObjectName(QString::fromUtf8("playList"));
        playList->setGeometry(QRect(510, 230, 331, 331));
        playList->setAcceptDrops(true);
        playList->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0.010, x2:0, y2:1, stop:0.960227 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"));
        playList->setDragEnabled(true);
        playList->setDragDropMode(QAbstractItemView::DragDrop);
        playList->setDefaultDropAction(Qt::MoveAction);
        playList->setAlternatingRowColors(false);
        playList->setSelectionMode(QAbstractItemView::ExtendedSelection);
        playlistParamTableView = new QTableView(mainWindow);
        playlistParamTableView->setObjectName(QString::fromUtf8("playlistParamTableView"));
        playlistParamTableView->setGeometry(QRect(700, 570, 131, 61));
        playlistParamTableView->setStyleSheet(QString::fromUtf8("background-color: rgb(169, 169, 169);"));
        randomPlaying = new QCheckBox(mainWindow);
        randomPlaying->setObjectName(QString::fromUtf8("randomPlaying"));
        randomPlaying->setGeometry(QRect(700, 570, 101, 21));
        invertPlaySeq = new QCheckBox(mainWindow);
        invertPlaySeq->setObjectName(QString::fromUtf8("invertPlaySeq"));
        invertPlaySeq->setGeometry(QRect(700, 590, 131, 21));
        startTrackPaused = new QCheckBox(mainWindow);
        startTrackPaused->setObjectName(QString::fromUtf8("startTrackPaused"));
        startTrackPaused->setGeometry(QRect(700, 610, 131, 21));
        deleteTracks = new QPushButton(mainWindow);
        deleteTracks->setObjectName(QString::fromUtf8("deleteTracks"));
        deleteTracks->setGeometry(QRect(510, 600, 91, 31));
        savePlayList = new QPushButton(mainWindow);
        savePlayList->setObjectName(QString::fromUtf8("savePlayList"));
        savePlayList->setGeometry(QRect(600, 600, 81, 31));
        loadPlayList = new QPushButton(mainWindow);
        loadPlayList->setObjectName(QString::fromUtf8("loadPlayList"));
        loadPlayList->setGeometry(QRect(600, 570, 81, 31));
        repeatTrack = new QCheckBox(mainWindow);
        repeatTrack->setObjectName(QString::fromUtf8("repeatTrack"));
        repeatTrack->setGeometry(QRect(400, 580, 91, 21));
        compGain = new QDial(mainWindow);
        compGain->setObjectName(QString::fromUtf8("compGain"));
        compGain->setGeometry(QRect(570, 40, 41, 41));
        compGain->setMinimum(-60);
        compGain->setMaximum(60);
        compGain->setPageStep(1);
        compAttack = new QDial(mainWindow);
        compAttack->setObjectName(QString::fromUtf8("compAttack"));
        compAttack->setGeometry(QRect(620, 60, 41, 41));
        compAttack->setMinimum(1);
        compAttack->setMaximum(50000);
        compAttack->setPageStep(5);
        compAttack->setValue(1000);
        compRelease = new QDial(mainWindow);
        compRelease->setObjectName(QString::fromUtf8("compRelease"));
        compRelease->setGeometry(QRect(670, 60, 41, 41));
        compRelease->setMinimum(50);
        compRelease->setMaximum(3000);
        compRelease->setPageStep(10);
        compRelease->setValue(200);
        compRatio = new QDial(mainWindow);
        compRatio->setObjectName(QString::fromUtf8("compRatio"));
        compRatio->setGeometry(QRect(740, 60, 41, 41));
        compRatio->setMinimum(1);
        compRatio->setMaximum(100);
        compRatio->setPageStep(1);
        compRatio->setValue(3);
        compPreDelay = new QDial(mainWindow);
        compPreDelay->setObjectName(QString::fromUtf8("compPreDelay"));
        compPreDelay->setGeometry(QRect(790, 30, 41, 41));
        compPreDelay->setMinimum(0);
        compPreDelay->setMaximum(40);
        compPreDelay->setPageStep(1);
        compPreDelay->setValue(0);
        compThreshold = new QDial(mainWindow);
        compThreshold->setObjectName(QString::fromUtf8("compThreshold"));
        compThreshold->setGeometry(QRect(740, 20, 41, 41));
        compThreshold->setMinimum(-60);
        compThreshold->setMaximum(0);
        compThreshold->setPageStep(1);
        compThreshold->setValue(-20);
        compOnOff = new QPushButton(mainWindow);
        compOnOff->setObjectName(QString::fromUtf8("compOnOff"));
        compOnOff->setGeometry(QRect(790, 70, 51, 24));
        label_8 = new QLabel(mainWindow);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(580, 30, 21, 16));
        label_8->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_35 = new QLabel(mainWindow);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(620, 50, 31, 16));
        label_35->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_36 = new QLabel(mainWindow);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(670, 50, 41, 16));
        label_36->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_37 = new QLabel(mainWindow);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(700, 20, 51, 21));
        label_37->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_38 = new QLabel(mainWindow);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(720, 60, 31, 16));
        label_38->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        label_39 = new QLabel(mainWindow);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(790, 20, 51, 16));
        label_39->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        playposSlider = new QSlider(mainWindow);
        playposSlider->setObjectName(QString::fromUtf8("playposSlider"));
        playposSlider->setGeometry(QRect(300, 190, 461, 21));
        playposSlider->setCursor(QCursor(Qt::ArrowCursor));
        playposSlider->setAcceptDrops(true);
        playposSlider->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        playposSlider->setMinimum(1);
        playposSlider->setMaximum(300);
        playposSlider->setPageStep(1);
        playposSlider->setSliderPosition(100);
        playposSlider->setOrientation(Qt::Horizontal);
        label_40 = new QLabel(mainWindow);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(80, 600, 181, 20));
        label_40->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.943455, y1:0.983, x2:0.96, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));"));
        clockSec = new QLCDNumber(mainWindow);
        clockSec->setObjectName(QString::fromUtf8("clockSec"));
        clockSec->setGeometry(QRect(810, 180, 31, 21));
        clockSec->setStyleSheet(QString::fromUtf8("background-color: rgb(73, 73, 73);\n"
""));
        clockSec->setNumDigits(2);
        clockMinMax = new QLCDNumber(mainWindow);
        clockMinMax->setObjectName(QString::fromUtf8("clockMinMax"));
        clockMinMax->setGeometry(QRect(770, 200, 40, 21));
        clockMinMax->setStyleSheet(QString::fromUtf8("background-color: rgb(20, 20, 20);\n"
""));
        clockMinMax->setNumDigits(3);
        clockSecMax = new QLCDNumber(mainWindow);
        clockSecMax->setObjectName(QString::fromUtf8("clockSecMax"));
        clockSecMax->setGeometry(QRect(810, 200, 31, 21));
        clockSecMax->setStyleSheet(QString::fromUtf8("background-color: rgb(20, 20, 20);\n"
""));
        clockSecMax->setNumDigits(2);
        trackInfo1 = new QLineEdit(mainWindow);
        trackInfo1->setObjectName(QString::fromUtf8("trackInfo1"));
        trackInfo1->setGeometry(QRect(300, 110, 551, 31));
        QFont font;
        font.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font.setPointSize(11);
        font.setBold(true);
        font.setWeight(75);
        trackInfo1->setFont(font);
        trackInfo1->setCursor(QCursor(Qt::ArrowCursor));
        trackInfo1->setStyleSheet(QString::fromUtf8("background-color: rgba(0, 0, 0, 225);\n"
"color: rgb(255, 255, 255);\n"
"border-top-color: rgb(0, 0, 0);\n"
"border-color: rgb(2, 2, 2);\n"
"selection-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);\n"
"gridline-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
""));
        trackInfo1->setReadOnly(true);
        trackInfo2 = new QLineEdit(mainWindow);
        trackInfo2->setObjectName(QString::fromUtf8("trackInfo2"));
        trackInfo2->setGeometry(QRect(300, 140, 551, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Segoe UI"));
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        trackInfo2->setFont(font1);
        trackInfo2->setCursor(QCursor(Qt::ArrowCursor));
        trackInfo2->setStyleSheet(QString::fromUtf8("background-color: rgab(0, 0, 0, 242);\n"
"border-color: rgb(2, 2, 2);\n"
"selection-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);\n"
"gridline-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        trackInfo2->setReadOnly(true);
        sysInfo1 = new QLineEdit(mainWindow);
        sysInfo1->setObjectName(QString::fromUtf8("sysInfo1"));
        sysInfo1->setGeometry(QRect(330, 610, 131, 21));
        sysInfo1->setFont(font1);
        sysInfo1->setCursor(QCursor(Qt::ArrowCursor));
        sysInfo1->setStyleSheet(QString::fromUtf8("background-color: rgab(0, 0, 0, 212);\n"
"color: rgb(255, 255, 255);"));
        sysInfo1->setReadOnly(true);
        sysInfo2 = new QLineEdit(mainWindow);
        sysInfo2->setObjectName(QString::fromUtf8("sysInfo2"));
        sysInfo2->setGeometry(QRect(330, 630, 131, 21));
        sysInfo2->setFont(font1);
        sysInfo2->setCursor(QCursor(Qt::ArrowCursor));
        sysInfo2->setStyleSheet(QString::fromUtf8("background-color: rgab(0, 0, 0, 212);\n"
"color: rgb(255, 255, 255);"));
        sysInfo2->setReadOnly(true);
        MainWindow->setCentralWidget(mainWindow);
        wreverbTable->raise();
        wreverbTxt->raise();
        echoTable->raise();
        flangerTable->raise();
        chorusTable->raise();
        gargleTable->raise();
        distTable->raise();
        timeBar->raise();
        echoTxt->raise();
        flangerTxt->raise();
        chorusTxt->raise();
        gargleTxt->raise();
        distTxt->raise();
        clockMin->raise();
        wreverbHFTimeRatio->raise();
        wreverbGain->raise();
        wreverbMix->raise();
        wreverbTime->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        slidersTableView->raise();
        volumeSlider->raise();
        pbspeedSlider->raise();
        label_5->raise();
        label_6->raise();
        playButton->raise();
        wreverbOnOff->raise();
        flangerOnOff->raise();
        distOnOff->raise();
        gargleOnOff->raise();
        chorusOnOff->raise();
        echoOnOff->raise();
        stopButton->raise();
        previousButton->raise();
        nextButton->raise();
        addFilesButton->raise();
        disableAllButton->raise();
        copyrightTableView->raise();
        label_7->raise();
        flangerWDMix->raise();
        flangerDepth->raise();
        flangerFreq->raise();
        flangerTWForm->raise();
        flangerFDBack->raise();
        flangerDelay->raise();
        flangerPhase->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        label_13->raise();
        label_14->raise();
        label_15->raise();
        distGain->raise();
        label_16->raise();
        distEdge->raise();
        label_17->raise();
        distPEQCFreq->raise();
        label_18->raise();
        distPEQBandw->raise();
        label_19->raise();
        distPreLPCutOff->raise();
        label_20->raise();
        gargleRateHZ->raise();
        label_21->raise();
        gargleSWForm->raise();
        label_22->raise();
        echoWDMix->raise();
        label_23->raise();
        echoFDBack->raise();
        label_24->raise();
        echoLDelay->raise();
        label_25->raise();
        echoRDelay->raise();
        label_26->raise();
        echoPanDelay->raise();
        label_27->raise();
        chorusWDMix->raise();
        label_28->raise();
        chorusDepth->raise();
        label_29->raise();
        chorusFDBack->raise();
        label_30->raise();
        chorusFreq->raise();
        label_31->raise();
        chorusDelay->raise();
        label_32->raise();
        chorusSWForm->raise();
        label_33->raise();
        chorusPhase->raise();
        label_34->raise();
        keepVolume->raise();
        keepPBSpeed->raise();
        keepEffectsOn->raise();
        line->raise();
        volumeLCD->raise();
        pbspeedLCD->raise();
        compTable->raise();
        compTxt->raise();
        playList->raise();
        playlistParamTableView->raise();
        randomPlaying->raise();
        invertPlaySeq->raise();
        startTrackPaused->raise();
        deleteTracks->raise();
        savePlayList->raise();
        loadPlayList->raise();
        repeatTrack->raise();
        compGain->raise();
        compAttack->raise();
        compRelease->raise();
        compRatio->raise();
        compPreDelay->raise();
        compThreshold->raise();
        compOnOff->raise();
        label_8->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        playposSlider->raise();
        label_40->raise();
        clockSec->raise();
        clockMinMax->raise();
        clockSecMax->raise();
        trackInfo1->raise();
        trackInfo2->raise();
        sysInfo1->raise();
        sysInfo2->raise();
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Helll Player v6.11b", 0, QApplication::UnicodeUTF8));
        wreverbTxt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#fefefe;\">Waves Reverb</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        echoTxt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#fdfdfd;\">Echo / Delay</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        flangerTxt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Flanger</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        chorusTxt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Distortion</span></p><p><br/></p></body></html>", 0, QApplication::UnicodeUTF8));
        gargleTxt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Gargle</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        distTxt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Chorus</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Gain", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "Mix", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "Rvb. Time", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "HF Time Ratio", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Volume</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Play Speed</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        playButton->setText(QApplication::translate("MainWindow", "Play / Pause", 0, QApplication::UnicodeUTF8));
        wreverbOnOff->setText(QApplication::translate("MainWindow", "OFF", 0, QApplication::UnicodeUTF8));
        flangerOnOff->setText(QApplication::translate("MainWindow", "OFF", 0, QApplication::UnicodeUTF8));
        distOnOff->setText(QApplication::translate("MainWindow", "OFF", 0, QApplication::UnicodeUTF8));
        gargleOnOff->setText(QApplication::translate("MainWindow", "OFF", 0, QApplication::UnicodeUTF8));
        chorusOnOff->setText(QApplication::translate("MainWindow", "OFF", 0, QApplication::UnicodeUTF8));
        echoOnOff->setText(QApplication::translate("MainWindow", "OFF", 0, QApplication::UnicodeUTF8));
        stopButton->setText(QApplication::translate("MainWindow", "Stop", 0, QApplication::UnicodeUTF8));
        previousButton->setText(QApplication::translate("MainWindow", "Previous", 0, QApplication::UnicodeUTF8));
        nextButton->setText(QApplication::translate("MainWindow", "Next", 0, QApplication::UnicodeUTF8));
        addFilesButton->setText(QApplication::translate("MainWindow", "Add Files to Play", 0, QApplication::UnicodeUTF8));
        disableAllButton->setText(QApplication::translate("MainWindow", "Disable All Effects", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; text-decoration: underline;\">Criado por: Jefferson Sales \302\251 - 2012.1</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "WD Mix", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "Depth", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "FDBack", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "Freq.", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "TWForm", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "Delay", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "Phase", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindow", "Gain", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MainWindow", "Edge", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("MainWindow", "PEQCFreq", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindow", "PEQBandW", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindow", "PreLPCutOff", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MainWindow", "RateHZ", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MainWindow", "SWForm", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MainWindow", "WD Mix", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("MainWindow", "FDBack", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindow", "LDelay", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindow", "RDelay", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MainWindow", "PanDelay", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("MainWindow", "WDMix", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindow", "Depth", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("MainWindow", "FDBack", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("MainWindow", "Freq.", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("MainWindow", "Delay", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("MainWindow", "SWForm", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("MainWindow", "Phase", 0, QApplication::UnicodeUTF8));
        keepVolume->setText(QApplication::translate("MainWindow", "Keep Volume", 0, QApplication::UnicodeUTF8));
        keepPBSpeed->setText(QApplication::translate("MainWindow", "Keep PB Speed", 0, QApplication::UnicodeUTF8));
        keepEffectsOn->setText(QApplication::translate("MainWindow", "Keep Effects On", 0, QApplication::UnicodeUTF8));
        compTxt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#fdfdfd;\">Compressor</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        randomPlaying->setText(QApplication::translate("MainWindow", "Random Playing", 0, QApplication::UnicodeUTF8));
        invertPlaySeq->setText(QApplication::translate("MainWindow", "Invert Play Sequence", 0, QApplication::UnicodeUTF8));
        startTrackPaused->setText(QApplication::translate("MainWindow", "Start Track Paused", 0, QApplication::UnicodeUTF8));
        deleteTracks->setText(QApplication::translate("MainWindow", "Delete Track(s)", 0, QApplication::UnicodeUTF8));
        savePlayList->setText(QApplication::translate("MainWindow", "Save PlayList", 0, QApplication::UnicodeUTF8));
        loadPlayList->setText(QApplication::translate("MainWindow", "Load PlayList", 0, QApplication::UnicodeUTF8));
        repeatTrack->setText(QApplication::translate("MainWindow", "Repeat Track", 0, QApplication::UnicodeUTF8));
        compOnOff->setText(QApplication::translate("MainWindow", "OFF", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "Gain", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("MainWindow", "Attack", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("MainWindow", "Release", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("MainWindow", "Threshold", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("MainWindow", "Ratio", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("MainWindow", "PreDelay", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("MainWindow", "jefferson360@gmail.com", 0, QApplication::UnicodeUTF8));
        trackInfo1->setText(QString());
        trackInfo2->setText(QString());
        sysInfo1->setText(QString());
        sysInfo2->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HELLL_H
